apps/travel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register$', views.register, name='register'),
	url(r'^login$', views.login, name='login'),	
	url(r'^logout$', views.logout, name='logout'),
	url(r'^travels$', views.dashboard, name='dashboard'),
	url(r'^travels/add$', views.add, name='add'),
	url(r'^travels/add/process$', views.process_add, name='process_add'),
	url(r'^travels/destination/(?P<id>\d+)$', views.show, name='show'),
	url(r'^travels/join/(?P<travel_id>\d+)$', views.process_join, name='process_join'),
]

blackbelt/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.travel.urls', namespace='travel')),
]

apps/travel/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
from datetime import datetime 



# Create your models here.
class UserManager(models.Manager):
	def validate_register(self, **k):
		errors = []
		if len(k['name']) < 3:
			errors.append('Name must be at least 3 characters long.')
		if len(k['username']) < 3:
			errors.append('Username must be at least 3 characters long.')
		if k['password'] != k['confirm_password']:
			errors.append('Passwords do not match.')
		if len(k['password']) < 8:
			errors.append('Password must be at least 8 characters long.')

		for error in errors:
			print error
		if errors: 
			return (False, errors)
		else:
			input_pw = k['password'].encode()
			hashed = bcrypt.hashpw(input_pw, bcrypt.gensalt())
			user = User.objects.create(name=k['name'], username=k['username'], password=hashed)
			return (True, user.id)

	def validate_login(self, **k):
		try:
			user = User.objects.get(username__iexact=k['username'])
			
			input_pw = k['password'].encode()
			hashed_pw = user.password.encode()

			if bcrypt.hashpw(input_pw, hashed_pw) == hashed_pw: 
				print '*'*50
				print user.id 
				return (True, user.id)
			else:
				return (False, 'Invalid Password')
		except:
			return (False, 'Invalid User/Login.')

class TravelManager(models.Manager):
	def validate_travel(self, **k):
		errors = []
		if len(k['destination']) < 1:
			errors.append('Destination cannot be blank.')
		if len(k['description']) < 1: 
			errors.append('You must enter a description.')
		if k['date_from'] == '':
			errors.append('You must enter a start date.')
		if k['date_to'] == '':
			errors.append('You must enter an end date.')

		if errors:
			return (False, errors)

		now = datetime.now()
		
		year = int(now.strftime('%Y'))
		month = int(now.strftime('%m'))
		day = int(now.strftime('%d'))

		df_year = int(k['date_from'][:4])
		df_month = int(k['date_from'][5:7])
		df_day = int(k['date_from'][8:10])

		dt_year = int(k['date_to'][:4])
		dt_month = int(k['date_to'][5:7])
		dt_day = int(k['date_to'][8:10])

		# 2016
		if year > df_year: 
			errors.append('It is the year '+str(year)+'. You must leave on a valid date.')

		if year == df_year:
			if month > df_month:
				errors.append('It is already month '+str(month)+'. You cannot leave on month '+str(df_month)+' without a time machine.')
		if year == df_year:
			if month == df_month:
				if day > df_day:
					errors.append('It is already day '+str(day)+' of the month. You cannot leave on day '+str(df_day)+' without a time machine.')

		if df_year > dt_year:
			errors.append('You cannot return before you leave.')

		if df_year == dt_year:
			if df_month > dt_month: 
				errors.append('You cannot return before you leave.')

		if df_year == dt_year:
			if df_month == dt_month:
				if df_day > dt_day:
					errors.append('You cannot return before you leave.')


		if errors:
			return (False, errors)
		else: 
			Travel.objects.create(destination=k['destination'], description=k['description'], date_from=k['date_from'], date_to=k['date_to'], user=k['user'])
			return (True, errors)
	def join_trip(self, **k):
		trip = Travel.objects.get(id=k['travel_id'])
		Travel.objects.create(destination=trip.destination, description=trip.description, date_from=trip.date_from, date_to=trip.date_to, user=k['user'])
		return 'Successfully Added Trip.'

class User(models.Model):
	name = models.CharField(max_length=45)
	username = models.CharField(max_length=255)
	password = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

class Travel(models.Model):
	destination = models.CharField(max_length=255)
	description = models.TextField(max_length=1000)
	user = models.ForeignKey(User, related_name='travelusers')
	date_from = models.DateField()
	date_to = models.DateField() 
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = TravelManager()

apps/travel/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import User, Travel

# Create your views here.
def index(request):
	# User.objects.all().delete()
	return render(request, 'travel/index.html')

def register(request):
	result = User.objects.validate_register(name=request.POST['name'], username=request.POST['username'], password=request.POST['password'], confirm_password=request.POST['confirm_password'])
	if result[0]:
		request.session['user_id'] = result[1]
		return redirect(reverse('travel:dashboard'))		
	else: 
		for error in result[1]:
			messages.error(request, error)
		return redirect(reverse('travel:index'))

def login(request):
	result = User.objects.validate_login(username=request.POST['username'], password=request.POST['password'])
	if result[0]:
		request.session['user_id'] = result[1]
		return redirect(reverse('travel:dashboard'))
	else:
		messages.error(request, result[1])
		return redirect(reverse('travel:index'))

def dashboard(request):
	try: 
		user = User.objects.get(id=request.session['user_id'])
		trips = Travel.objects.filter(user=user)
		all_trips = Travel.objects.exclude(user=user)

		other_trips = []
		for dest in all_trips:
			found = False
			for trip in trips:
				if trip.destination == dest.destination:  
					found = True
			if not found:
				other_trips.append(dest)

		context = {
			'user': user,
			'trips': trips,
			'other_trips': other_trips,
		}
		return render(request, 'travel/dashboard.html', context)
	except:
		return redirect(reverse('travel:index'))	

def logout(request):
	request.session.clear()
	return redirect(reverse('travel:index'))

def add(request):
	return render(request, 'travel/add.html')

def process_add(request):
	user = User.objects.get(id=request.session['user_id'])
	result = Travel.objects.validate_travel(destination=request.POST['destination'], description=request.POST['description'], user=user, date_from=request.POST['date_from'], date_to=request.POST['date_to'])
	if result[0]:
		return redirect(reverse('travel:dashboard'))
	else: 
		for error in result[1]:
			messages.error(request, error)
	return redirect(reverse('travel:add'))

def show(request, id):
	trip = Travel.objects.get(id=id)
	trip_creator = Travel.objects.filter(destination=trip.destination).order_by('created_at').distinct()

	all_users = Travel.objects.filter(destination=trip.destination)

	users = []
	current = User.objects.get(id=request.session['user_id'])
	users.append(current)

	for user in all_users:
		found = False
		for i in users:
			if i.name == user.user.name:
				found = True
		if not found:
			users.append(user.user)
	users.pop(0)

	context = {
		'trip': trip_creator[0],
		'users': users,
	}
	return render(request, 'travel/show.html', context)

def process_join(request, travel_id):
	user = User.objects.get(id=request.session['user_id'])
	result = Travel.objects.join_trip(travel_id=travel_id, user=user)
	messages.success(request, result)
	return redirect(reverse('travel:dashboard'))

apps/travel/templates/travel/add.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8'>
	<meta name='content' description='Travel app in Django'>
	<title>Add Plan</title>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
	{% load staticfiles %}
	<link rel='stylesheet' type='text/css' href='{% static "travel/styles/style.css" %}'>
</head>
<body>
	<div class='container add'>
		<form class='header' action='{% url "travel:logout" %}' method='GET'>
			<input class='btn btn-default' type='submit' value='Logout'>
		</form>
		<form class='header' action='{% url "travel:dashboard" %}' method='GET'>
			<input class='btn btn-default' type='submit' value='Home'>
		</form>
		<h1>Add A Trip</h1>
		<form class='travel_details' action='{% url "travel:process_add" %}' method='POST'>
		{% csrf_token %}
			<label>Destination:</label>
			<input type='text' name='destination'>
			<label>Description:</label>
			<input type='text' name='description'>
			<label>Travel Date From:</label>
			<input type='date' name='date_from'>
			<label>Return Date :</label>
			<input type='date' name='date_to'>
			<input class='btn btn-default' type='submit' value='Add'>
		</form>
		<div class='messages'>
 			{% for message in messages %}
 				<p {% if message.tags %} class='{{message.tags}}' {% endif %}>{{message}}</p>
 			{% endfor %}
 		</div>
	</div>
</body>
</html>

apps/travel/templates/travel/dashboard.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8'>
	<meta name='content' description='Travel app in Django'>
	<title>Travel Dashbaord</title>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
	{% load staticfiles %}
	<link rel='stylesheet' type='text/css' href='{% static "travel/styles/style.css" %}'>
</head>
<body>
	<div class='container'>
		<form class='header' action='{% url "travel:logout" %}' method='GET'>
			<input class='btn btn-default' type='submit' value='Logout'>
		</form>
		<h1>Hello {{user.name}}</h1>
		<div class='success'>
			{% for message in messages %}
				<p {% if message.tags %} class='{{message.tag}}' {% endif %}>{{message}}</p>
			{% endfor %}
		</div>
		<h3>Your Trip Schedules</h3>
		<table class='table schedule'>
			<thead>
				<tr>
					<th>Destination</th>
					<th>Travel Start Date</th>
					<th>Travel End Date</th>
					<th>Plan</th>
				</tr>
			</thead>
			<tbody>
				{% for trip in trips %}
				<tr>
					<td><a href='{% url "travel:show" trip.id %}'>{{trip.destination}}</a></td>
					<td>{{trip.date_from}}</td>
					<td>{{trip.date_to}}</td>
					<td>{{trip.description}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		
		<h3>Other User's Travel Plans</h3>
		<table class='table others'>
			<thead>
				<tr>
					<th>Name</th>
					<th>Destination</th>
					<th>Travel Start Date</th>
					<th>Travel End Date</th>
					<th>Do You Want To Join?</th>
				</tr>
			</thead>
			<tbody>
				{% for trip in other_trips %}
				<tr>
					<td>{{trip.user.name}}</td>
					<td>{{trip.destination}}</td>
					<td>{{trip.date_from}}</td>
					<td>{{trip.date_to}}</td>
					<td>
						<form action='{% url "travel:process_join" trip.id %}' method='POST'>
						{% csrf_token %}
							<input class='btn btn-default' type='submit' value='Join'>
						</form>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<form class='header' action='{% url "travel:add" %}' method='GET'>
			<input class='btn btn-default' type='submit' value='Add Travel Plan'>
		</form>
	</div>
</body>
</html>

apps/travel/templates/travel/index.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8'>
	<meta name='content' description='Travel app in Django'>
	<title>Login/Registration</title>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
	{% load staticfiles %}
	<link rel='stylesheet' type='text/css' href='{% static "travel/styles/style.css" %}'>
</head>
<body>
	<div class='container'>
		<h1>WELCOME</h1>
		<div class='register inline'>
			<h2>Register</h2>
			<form action='{% url "travel:register" %}' method='POST'>
			{% csrf_token %}
				<label>Name:</label>
				<input type='text' name='name'>
				<label>Username:</label>
				<input type='text' name='username'>
				<label>Password:</label>
				<input type='password' name='password'>
				<label>Confirm Password:</label>
				<input type='password' name='confirm_password'>
				<input class='btn btn-default' type='submit' value='Register'>
			</form>
 		</div>
 		<div class='login inline'>
 			<h2>Login</h2>
 			<form action='{% url "travel:login" %}' method='POST'>
 			{% csrf_token %}
	 			<label>Username:</label>
				<input type='text' name='username'>
				<label>Password:</label>
				<input type='password' name='password'>
				<input class='btn btn-default' type='submit' value='Login'> 				
 			</form>
 		</div>
 		<div class='messages'>
 			{% for message in messages %}
 				<p {% if message.tags %} class='{{message.tags}}' {% endif %}>{{message}}</p>
 			{% endfor %}
 		</div>
	</div>
</body>
</html>

apps/travel/templates/travel/show.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8'>
	<meta name='content' description='Travel app in Django'>
	<title></title>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
	{% load staticfiles %}
	<link rel='stylesheet' type='text/css' href='{% static "travel/styles/style.css" %}'>
</head>
<body>
	<div class='container show'>
		<form class='header' action='{% url "travel:logout" %}' method='GET'>
			<input class='btn btn-default' type='submit' value='Logout'>
		</form>
		<form class='header' action='{% url "travel:dashboard" %}' method='GET'>
			<input class='btn btn-default' type='submit' value='Home'>
		</form>
		<h1>{{trip.destination}}</h1>
		<div class='marginleft30'>
			<p>Planned by: {{trip.user.name}}</p>
			<p>Description: {{trip.description}}</p>
			<p>Travel Date From: {{trip.date_from}}</p>
			<p>Travel Date To: {{trip.date_to}}</p>
		</div>

		<h1 class='margintop50'>Other User's Joining The Trip:</h1>
		<div class='marginleft30'>
		{% for user in users %}
			<p>{{user.name}}</p>
		{% endfor %}
		</div>

	</div>
</body>
</html>